import { useEffect, useMemo, useState } from 'react';
import { getQuestions, getSubjects } from '../data/questionLoader';
import { loadTestState, saveTestState, clearTestState } from '../utils/testStorage';
import { calculateTestResult, formatDuration } from '../utils/analytics';
import { saveTestResult } from '../utils/analyticsStorage';

const makeState = (questions, duration) => ({status:'config',questions,current:0,answers:{},marked:{},startedAt:null,remainingSeconds:duration*60,durationSeconds:duration*60});

export default function MockTest() {
  const [subject,setSubject]=useState(''); const [count,setCount]=useState(10); const [duration,setDuration]=useState(15);
  const [state,setState]=useState(()=>loadTestState()); const [result,setResult]=useState(null);
  const questions=useMemo(()=>getQuestions({subject}).slice(0,Number(count)),[subject,count]);

  useEffect(()=>{ if(!state||state.status!=='running')return; const id=setInterval(()=>setState(prev=>{if(!prev||prev.status!=='running')return prev;if(prev.remainingSeconds<=1)return {...prev,status:'submitted',remainingSeconds:0};return {...prev,remainingSeconds:prev.remainingSeconds-1};}),1000);return()=>clearInterval(id)},[state?.status]);
  useEffect(()=>{if(state)saveTestState(state)},[state]);

  function start(){if(!questions.length)return;setResult(null);setState({...makeState(questions,Number(duration)),status:'running',startedAt:Date.now()})}
  function answer(i){setState(prev=>({...prev,answers:{...prev.answers,[prev.current]:i}}))}
  function toggleMark(){setState(prev=>({...prev,marked:{...prev.marked,[prev.current]:!prev.marked[prev.current]}}))}
  function submit(){setState(prev=>({...prev,status:'submitted'}))}
  function restart(){clearTestState();setState(null);setResult(null)}

  useEffect(()=>{if(state?.status==='submitted'&&!result){const calculated=calculateTestResult(state);setResult(calculated);saveTestResult({...calculated,subject:subject||'All subjects',completedAt:new Date().toISOString()})}},[state?.status,result,subject]);

  if(state?.status==='running'){const q=state.questions[state.current];const answered=Object.keys(state.answers).length;const marked=Object.values(state.marked).filter(Boolean).length;const mins=Math.floor(state.remainingSeconds/60).toString().padStart(2,'0');const secs=(state.remainingSeconds%60).toString().padStart(2,'0');return <div className="mock-wrap"><div className="mock-header"><button className="btn secondary" onClick={submit}>Submit</button><strong>{mins}:{secs}</strong><span>{answered}/{state.questions.length} answered</span></div><div className="mock-body"><div className="palette card">{state.questions.map((item,i)=><button key={item.id} className={`palette-btn ${state.current===i?'current ':''}${state.answers[i]!==undefined?'answered ':''}${state.marked[i]?'marked':''}`} onClick={()=>setState(s=>({...s,current:i}))}>{i+1}</button>)}</div><article className="question-card card"><div className="question-meta"><span>Q {state.current+1}</span><span>{q.subject}</span><span>{q.difficulty}</span></div><h2>{q.question}</h2><div className="options">{q.options.map((option,i)=><button key={option} className={`option${state.answers[state.current]===i?' selected':''}`} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div><div className="mock-actions"><button className="btn secondary" onClick={()=>setState(s=>({...s,current:Math.max(0,s.current-1)}))} disabled={state.current===0}>← Previous</button><button className={state.marked[state.current]?'btn primary':'btn secondary'} onClick={toggleMark}>{state.marked[state.current]?'Marked':'Mark for review'}</button><button className="btn primary" onClick={()=>setState(s=>({...s,current:Math.min(s.questions.length-1,s.current+1)}))}>{state.current===state.questions.length-1?'Last':'Next →'}</button></div><div className="mock-legend"><span>Answered: {answered}</span><span>Review: {marked}</span></div></article></div></div>}

  if(state?.status==='submitted'&&result){return <div className="page-title"><span className="eyebrow">Test Analytics</span><h1>Mock Test Result</h1><div className="result-hero card"><strong>{result.correct}/{result.total}</strong><span>Score</span><div className="result-metrics"><span>Accuracy <b>{result.accuracy}%</b></span><span>Attempted <b>{result.attempted}</b></span><span>Wrong <b>{result.wrong}</b></span><span>Unanswered <b>{result.unanswered}</b></span><span>Time <b>{formatDuration(result.timeUsedSeconds)}</b></span></div></div><h2>Subject Breakdown</h2><div className="analytics-list">{Object.entries(result.bySubject).map(([name,v])=><div className="card analytics-row" key={name}><strong>{name}</strong><span>{v.correct}/{v.attempted} correct</span><b>{v.accuracy}%</b></div>)}</div><h2>Topic Breakdown</h2><div className="analytics-list">{Object.entries(result.byTopic).map(([name,v])=><div className="card analytics-row" key={name}><strong>{name}</strong><span>{v.correct}/{v.attempted} correct</span><b>{v.accuracy}%</b></div>)}</div><button className="btn primary" onClick={restart}>Start New Test</button></div>}

  return <><div className="page-title"><span className="eyebrow">CBT Mock Test</span><h1>Configure Test</h1><p className="muted">Timer, palette, review marking and local state restore are enabled.</p></div><div className="card practice-filters"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">All subjects</option>{getSubjects().map(s=><option key={s}>{s}</option>)}</select></label><label>Questions<select value={count} onChange={e=>setCount(e.target.value)}>{[10,20,30,50].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Time<select value={duration} onChange={e=>setDuration(e.target.value)}>{[10,15,30,45,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><button className="btn primary start-btn" onClick={start} disabled={!questions.length}>Start CBT ({questions.length})</button></div>{!questions.length&&<div className="card empty"><h3>No questions available</h3><p className="muted">Add valid question data before starting a mock.</p></div>}</>
}
